/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Person {
  'id' : bigint,
  'name' : string,
  'note' : string,
  'amount' : number,
}
export interface Transaction {
  'id' : bigint,
  'date' : string,
  'note' : string,
  'createdAt' : bigint,
  'type' : string,
  'debtPerson' : string,
  'category' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPerson' : ActorMethod<[string, number, string], bigint>,
  'addTransaction' : ActorMethod<
    [string, number, string, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePerson' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'editPerson' : ActorMethod<[bigint, string, number, string], undefined>,
  'editTransaction' : ActorMethod<
    [bigint, string, number, string, string, string, string],
    undefined
  >,
  'getAllPeople' : ActorMethod<[], Array<Person>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactionsByMonth' : ActorMethod<[bigint, bigint], Array<Transaction>>,
  'getTransactionsByWeek' : ActorMethod<[bigint, bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];