/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Person = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'note' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'type' : IDL.Text,
  'debtPerson' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPerson' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [IDL.Nat], []),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePerson' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'editPerson' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64, IDL.Text], [], []),
  'editTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactionsByMonth' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByWeek' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Person = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'note' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'type' : IDL.Text,
    'debtPerson' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPerson' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [IDL.Nat], []),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePerson' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'editPerson' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64, IDL.Text], [], []),
    'editTransaction' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactionsByMonth' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByWeek' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };